### ISSUE TITLE
Include final app in secondary branch

### ISSUE THREAD

**Issue by fabian57fabian** [MirkoRaimo/flutter_list_starting_point#1]
One could include the final app behaviour and code inside a parallel branch from [this repo](https://github.com/MirkoRaimo/flutter_list_arrival_point)

**Comment by MirkoRaimo** [comment]
Hi @fabian57fabian,
you had a great idea!

I created the branch <a href="https://github.com/MirkoRaimo/flutter_list_starting_point/tree/arrival_point">arrival_point</a> to keep all the code inside this repository.

Best regards
Mirko
